#!/bin/bash
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-slate-950/bg-background/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-slate-50/text-foreground/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-slate-300/text-foreground\/90/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-slate-400/text-muted-foreground/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-slate-500/text-muted-foreground\/70/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/border-slate-800/border-border/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/border-slate-700/border-border\/80/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-slate-900/bg-card/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-slate-800/bg-secondary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/hover:bg-slate-800/hover:bg-secondary\/80/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/hover:bg-slate-700/hover:bg-secondary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-blue-400/text-primary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-blue-600/bg-primary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/hover:bg-blue-700/hover:bg-primary\/90/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-blue-500/bg-primary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/border-blue-500/border-primary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/ring-blue-500/ring-primary/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-emerald-400/text-[var(--chart-2)]/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-emerald-500/bg-[var(--chart-2)]/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-red-400/text-destructive/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/text-amber-500/text-[var(--chart-5)]/g' {} +
find src -type f -name "*.tsx" -exec sed -i '' -e 's/bg-amber-500/bg-[var(--chart-5)]/g' {} +
