const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const questions = [
  { topic: 'Equities', difficulty: 'HARD', text: 'Which of the following corporate actions does NOT affect the stock price directly?', options: JSON.stringify(['Stock Split', 'Dividend Declaration', 'Change in Statutory Auditor', 'Bonus Issue']), correctIndex: 2, explanation: 'Auditor changes are administrative, whereas splits, dividends, and bonuses mathematically adjust the per-share value.' },
  { topic: 'Bonds', difficulty: 'EASY', text: 'What is a bond coupon?', options: JSON.stringify(['A discount voucher', 'The interest rate paid to the bondholder', 'The principal amount', 'The maturity date']), correctIndex: 1, explanation: 'The coupon is the annual interest rate paid on a bond, expressed as a percentage of the face value.' },
  { topic: 'REITs', difficulty: 'MEDIUM', text: 'In India, what percentage of a REITs net distributable cash flows must be distributed to unit holders?', options: JSON.stringify(['50%', '75%', '90%', '100%']), correctIndex: 2, explanation: 'SEBI mandates that REITs must distribute at least 90% of their net distributable cash flows to investors.' },
  { topic: 'InvITs', difficulty: 'MEDIUM', text: 'InvITs primarily invest in which type of assets?', options: JSON.stringify(['Gold and Silver', 'Infrastructure projects like toll roads and power grids', 'Startup equity', 'Foreign government bonds']), correctIndex: 1, explanation: 'Infrastructure Investment Trusts (InvITs) manage operational infrastructure assets.' },
  { topic: 'SIPs', difficulty: 'EASY', text: 'What is the primary benefit of a Systematic Investment Plan (SIP)?', options: JSON.stringify(['Guaranteed returns', 'Rupee cost averaging', 'Zero market risk', 'Tax evasion']), correctIndex: 1, explanation: 'SIPs help average out the purchase cost over time (Rupee cost averaging) and instill investing discipline.' },
  { topic: 'Mutual Funds', difficulty: 'MEDIUM', text: 'What does Expense Ratio represent in a mutual fund?', options: JSON.stringify(['The fee paid to enter the fund', 'The annual fee charged by the AMC to manage the fund', 'The tax deducted at source', 'The broker commission']), correctIndex: 1, explanation: 'The expense ratio is the annual fee that funds charge their shareholders to cover operating costs.' },
  { topic: 'Diversification', difficulty: 'EASY', text: 'Which phrase best describes diversification?', options: JSON.stringify(['Putting all eggs in one basket', 'Don\'t put all your eggs in one basket', 'Buying high and selling low', 'Chasing past performance']), correctIndex: 1, explanation: 'Diversification reduces risk by allocating investments across various financial instruments.' },
  { topic: 'Risk', difficulty: 'HARD', text: 'What does "Beta" measure in stock market investing?', options: JSON.stringify(['The dividend yield of a stock', 'A stock\'s volatility relative to the overall market', 'The fundamental value of a company', 'The inflation rate']), correctIndex: 1, explanation: 'Beta measures a security\'s volatility compared to the market. A beta > 1 means it is more volatile than the market.' },
  { topic: 'Equities', difficulty: 'MEDIUM', text: 'What is a Demat account used for?', options: JSON.stringify(['To hold money', 'To hold shares and securities in electronic format', 'To trade derivatives only', 'To avoid paying taxes']), correctIndex: 1, explanation: 'A Dematerialized (Demat) account holds shares and securities in electronic rather than physical form.' },
  { topic: 'Bonds', difficulty: 'HARD', text: 'If a bond\'s Yield to Maturity (YTM) is higher than its coupon rate, the bond is trading at:', options: JSON.stringify(['A premium', 'Par value', 'A discount', 'It is impossible']), correctIndex: 2, explanation: 'When a bond trades at a discount to its face value, its yield to maturity becomes higher than its coupon rate.' },
  { topic: 'SIPs', difficulty: 'HARD', text: 'In a declining market, what happens to your SIP installments?', options: JSON.stringify(['You buy fewer units', 'You buy more units', 'Your SIP stops automatically', 'The NAV remains constant']), correctIndex: 1, explanation: 'Because the Net Asset Value (NAV) drops in a declining market, the same SIP amount buys a higher number of units.' },
  { topic: 'REITs', difficulty: 'EASY', text: 'What does REIT stand for?', options: JSON.stringify(['Real Estate Investment Trust', 'Retail Equity Index Trading', 'Risk Evaluation Investment Tool', 'Real Earning Income Tax']), correctIndex: 0, explanation: 'REIT stands for Real Estate Investment Trust, allowing individuals to invest in large-scale real estate.' },
  { topic: 'Mutual Funds', difficulty: 'MEDIUM', text: 'What is the difference between Direct and Regular mutual funds?', options: JSON.stringify(['Direct funds have lower expense ratios as they bypass distributors', 'Regular funds guarantee higher returns', 'Direct funds are only for institutional investors', 'There is no difference']), correctIndex: 0, explanation: 'Direct plans do not pay commissions to distributors, resulting in lower expense ratios and better long-term returns.' }
];

async function main() {
  for (const q of questions) {
    await prisma.question.create({ data: q });
  }
  console.log("Added 13 more questions.");
}
main().finally(() => prisma.$disconnect());
